# api call for creating user
###
POST http://127.0.0.1:8000/admin-register/
Content-Type: application/json

{
    "username":"superuser",
    "email":"superuser@gmail.com",
    "password":"superuser"
}

# api call for listing all turfs
###
GET http://127.0.0.1:8000/turfs/
Accept: application/json
Authorization: Basic superuser:superuser

# api call for adding turfs
###
POST http://127.0.0.1:8000/turfs/
Content-Type: application/json
Authorization: Basic superuser:superuser

{
    "name":"Dreams",
    "location":"Chalakudy",
    "phone":987654321,
    "fee":1200
}

# api call for retrieveing specific turf
###
GET http://127.0.0.1:8000/turfs/2/
Accept: application/json
Authorization: Basic superuser:superuser

# api call for adding turfs
###
PUT http://127.0.0.1:8000/turfs/2/
Content-Type: application/json
Authorization: Basic superuser:superuser

{
    "name":"Dreams",
    "location":"Chalakudy",
    "phone":987654321,
    "fee":1100
}

# BOOKINGS ==============================

# api call for listing all bookings
###
GET http://127.0.0.1:8000/bookings/
Accept: application/json


# BOOKINGS V2 ===============================

# customer register api
###
POST http://127.0.0.1:8000/v2/booking/signup/
Content-Type: application/json

{
    "username":"habeeb",
    "email":"habeeb@gmail.com",
    "password":"habeeb@123"
    
}

# listing bookings api call
###
GET http://127.0.0.1:8000/v2/booking/bookings/
Accept: application/json

# creating new booking api call
###
POST http://127.0.0.1:8000/v2/booking/bookings/
Content-Type: application/json

{
    "customer_name":"manoj",
    "turf":2,
    "booking_date":"2026-10-20",
    "start_time":"14:00",
    "duration":1,
    "phone_number":123456789,
    "email":"rahul@gamil.com"
}