# Generated by Django 5.2.17 on 2026-10-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='duration',
            field=models.DurationField(),
        ),
    ]
